version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./meta:/usr/local/planetviewer/data
      - es-certs:/usr/local/planetviewer/certs
    environment:
      - APP_DATA_DIR=/usr/local/planetviewer/data

      # Default user used by the image. See
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html#built-in-users
      - ELASTIC_USERNAME=elastic
      # https://discuss.elastic.co/t/set-password-and-user-with-docker-compose/225075/2
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOST=es
      - ELASTIC_CA_CERT_PATH=/usr/local/planetviewer/certs/ca/ca.crt
      - ELASTIC_PORT=9200

      # PostgreSQL-related envars.
      - POSTGRES_URL=jdbc:postgresql://db:5432/planetviewer
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      es:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
    # More info: https://github.com/docker-library/docs/blob/master/postgres/README.md
      - POSTGRES_DB=planetviewer
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "planetviewer"]
      interval: 10s
      timeout: 5s
      retries: 5

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    restart: unless-stopped
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-certs:${ELASTIC_CERTS_DIR}
    environment:
      # https://discuss.elastic.co/t/set-password-and-user-with-docker-compose/225075/2
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # Form a single-node cluster.
      - discovery.type=single-node
      # https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html#_set_the_heap_size
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=${ELASTIC_CERTS_DIR}/es/es.key
      - xpack.security.http.ssl.certificate_authorities=${ELASTIC_CERTS_DIR}/ca/ca.crt
      - xpack.security.http.ssl.certificate=${ELASTIC_CERTS_DIR}/es/es.crt

    expose:
      - 9200
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "-u", "elastic:${ELASTIC_PASSWORD}", "https://localhost:9200/_cluster/health"]
      interval: 16s
      timeout: 10s
      retries: 5

volumes:
  db-data:
  es-data:
  es-certs:
    name: es-certs
    external: true
