version: '3.8'

volumes:
  postgres-data:


services:
  app:
    build:
      context: .
    volumes:
      - ../..:/workspaces:cached
    environment:
      APP_DATA_DIR: /workspaces/planetviewer

      # NOTE: POSTGRES_* should match values in db container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://db:5432/planetviewer

      ELASTIC_HOST: elasticsearch
      ELASTIC_PORT: 9200

    depends_on:
      - db
      - elasticsearch

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_USER/PASSWORD should match values in app container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planetviewer

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    restart: unless-stopped
    environment:
      # NOTE: This environment variable disables security entirely. Don't do this in production.
      - xpack.security.enabled=false
      # Form a single-node cluster.
      - discovery.type=single-node
